apiVersion: v1
kind: Service
metadata:
  name: juiceshop-svc
  labels:
    app: juice-shop
spec:
  type: NodePort
  ports:
  - port: 3000
    nodePort: 30001
    protocol: TCP
  selector:
    app: juice-shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juiceshop-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juice-shop
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: alsharma9/juice-shop:csg-boot
        ports:
        - containerPort: 8080
